#: import configurables configurables

<MainMenuScreen>:
    id: MainMenuScreen

    Background:
        id: bg
        size_hint: 1, 1

    FloatLayout:
        pos_hint: {"x":0, "top": 1}
        Label:
            text: "Defend The Skin"
            font_name: configurables.bgFontName
            font_size: 50
            bold: True

            pos_hint: {"x":0, "top": 1.05}
            size_hint: 1, 0.2

        Button:
            id: PlayButton

            text: "Play"
            font_name: configurables.bgFontName
            font_size:40
            bold: True

            background_color: 0, 0, 0, 0

            pos_hint: configurables.playButtonPos
            size_hint: configurables.playButtonSize

            on_release: MainMenuScreen.start_game()

        Label:
            text: "How To Play And How Is It About The Skin Immune System? \n \n The aim of the game is to destroy all the bricks while not hitting any antibodies. You do this by bouncing a ball ( virus ) against the bricks ( cells ) and the racket that you control, you also have to slide the racket into the zoomed in part of the cell that will appear when the ball hits a brick like how a virus has to attach itself to the proteins on the cell to get inside of it so it can start to reproduce"
            font_name: configurables.bgFontName
            font_size: 25
            bold: True
            valign: "top"
            halign: "center"
            multiline: True
            text_size: self.width * configurables.bgExplainerTextWidth, self.height

            pos_hint: {"x":0, "top": configurables.bgExplainerTextY}
            size_hint: 1, 1


<PlayScreen>:
    id: PlayScreen

    Background:
        id: bg
        size_hint: 1, 1
        playing: True

    AtariBricks:
        id: AtariBricks

    Ball:
        id: Ball

    BigBrick:
        id: BigBrick
        size_hint: configurables.bigBrickWidth, configurables.bigBrickHeight
        pos_hint: {"center_x": 0.5, "y": configurables.bigBrickHeight * -1}

    Racket:
        id: Racket

    Health:
        id: Health


<ScoreScreen>:
    id: ScoreScreen

    Background:
        id: bg
        size_hint: 1, 1

    FloatLayout:
        pos_hint: {"x":0, "top": 1}
        Label:
            text: "You Loose"
            font_name: configurables.bgFontName
            font_size: 50
            bold: True

            pos_hint: {"x":0, "top": 1.05}
            size_hint: 1, 0.2

        Label:
            id: Score

            text: "Your Score Is 0"
            font_name: configurables.bgFontName
            font_size:40
            bold: True

            pos_hint: configurables.playButtonPos
            size_hint: configurables.playButtonSize


        Button:
            id: PlayAgainButton

            text: "Click To Play Again"
            font_name: configurables.bgFontName
            font_size:40
            bold: True

            background_color: 0, 0, 0, 0

            pos_hint: {"x": 0, "y": 0}
            size_hint: 1, 1

            on_release: ScoreScreen.next()


<Racket>:
    pos_hint: {"y": configurables.racketY}
    on_size: self.center_x = self.parent.width / 2
    size_hint: configurables.racketSize

    canvas:
        Color:
            rgb: configurables.racketColor

        Rectangle:
            pos: self.pos
            size: self.size


<Ball>:
    y: configurables.ballY * self.parent.height
    center_x: self.parent.center_x

    size_hint: None, None

    canvas:
        Color:
            rgb: configurables.ballColor

        Rectangle:
            pos: self.pos
            size: self.size


<Health>:
    Image:
        id: heart_1
        source: "Resources/heart.png"
        allow_stretch: True

    Image:
        id: heart_2
        source: "Resources/heart.png"
        allow_stretch: True

    Image:
        id: heart_3
        source: "Resources/heart.png"
        allow_stretch: True
